item { 
	name :'AH'
	id : 1
}
item { 
	name :'2H'
	id : 2
}
item { 
	name :'3H'
	id : 3
}
item { 
	name :'4H'
	id : 4
}
item { 
	name :'5H'
	id : 5
}
item { 
	name :'6H'
	id : 6
}
item { 
	name :'7H'
	id : 7
}
item { 
	name :'8H'
	id : 8
}
item { 
	name :'9H'
	id : 9
}
item { 
	name :'10H'
	id : 10
}
item { 
	name :'JH'
	id : 11
}
item { 
	name :'QH'
	id : 12
}
item { 
	name :'KH'
	id : 13
}
item { 
	name :'AS'
	id : 14
}
item { 
	name :'2S'
	id : 15
}
item { 
	name :'3S'
	id : 16
}
item { 
	name :'4S'
	id : 17
}
item { 
	name :'5S'
	id : 18
}
item { 
	name :'6S'
	id : 19
}
item { 
	name :'7S'
	id : 20
}
item { 
	name :'8S'
	id : 21
}
item { 
	name :'9S'
	id : 22
}
item { 
	name :'10S'
	id : 23
}
item { 
	name :'JS'
	id : 24
}
item { 
	name :'QS'
	id : 25
}
item { 
	name :'KS'
	id : 26
}
item { 
	name :'AC'
	id : 27
}
item { 
	name :'2C'
	id : 28
}
item { 
	name :'3C'
	id : 29
}
item { 
	name :'4C'
	id : 30
}
item { 
	name :'5C'
	id : 31
}
item { 
	name :'6C'
	id : 32
}
item { 
	name :'7C'
	id : 33
}
item { 
	name :'8C'
	id : 34
}
item { 
	name :'9C'
	id : 35
}
item { 
	name :'10C'
	id : 36
}
item { 
	name :'JC'
	id : 37
}
item { 
	name :'QC'
	id : 38
}
item { 
	name :'KC'
	id : 39
}
item { 
	name :'AD'
	id : 40
}
item { 
	name :'2D'
	id : 41
}
item { 
	name :'3D'
	id : 42
}
item { 
	name :'4D'
	id : 43
}
item { 
	name :'5D'
	id : 44
}
item { 
	name :'6D'
	id : 45
}
item { 
	name :'7D'
	id : 46
}
item { 
	name :'8D'
	id : 47
}
item { 
	name :'9D'
	id : 48
}
item { 
	name :'10D'
	id : 49
}
item { 
	name :'JD'
	id : 50
}
item { 
	name :'QD'
	id : 51
}
item { 
	name :'KD'
	id : 52
}
